
/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */
package com.zeh.wms.dal.operation.user;

import com.zeh.jungle.dal.paginator.PageQuery;
import org.apache.commons.lang.builder.ToStringBuilder;
/**
 * database table: user
 * database table comments: User
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class GetAllUserPageQuery  extends PageQuery implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;
	
	/** 昵称 */
	private String nickName;
	/** 用户账号，用户电话 */
	private String userId;
	/** 用户手机号 */
	private String mobile;
	/** 创建时间 */
	private java.util.Date fromDate;
	/** 创建时间 */
	private java.util.Date toDate;
	
	public GetAllUserPageQuery() {
	}
	
	public GetAllUserPageQuery(String nickName ,String userId ,String mobile ,java.util.Date fromDate ,java.util.Date toDate ) {
		this.nickName = nickName;
		this.userId = userId;
		this.mobile = mobile;
		this.fromDate = fromDate;
		this.toDate = toDate;
	}
	
	public String getNickName() {
		return nickName;
	}
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}
	public String getUserId() {
		return userId;
	}
	public void setUserId(String userId) {
		this.userId = userId;
	}
	public String getMobile() {
		return mobile;
	}
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
	public java.util.Date getFromDate() {
		return fromDate;
	}
	public void setFromDate(java.util.Date fromDate) {
		this.fromDate = fromDate;
	}
	public java.util.Date getToDate() {
		return toDate;
	}
	public void setToDate(java.util.Date toDate) {
		this.toDate = toDate;
	}
	
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}
}
