/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */
package com.zeh.wms.dal.dataobject;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.zeh.jungle.dal.paginator.PageQuery;
import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.jungle.dal.paginator.PageQueryUtils;
/**
 * ExpressOrderDO
 * database table: express_order
 * database table comments: ExpressOrder
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class ExpressOrderDO implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;
	
	/**
	 * 主键 		db_column: id 
	 */
	private long id;
	/**
	 * 快递单号 		db_column: order_no 
	 */
	private String orderNo;
	/**
	 * 3方订单号 		db_column: other_order_no 
	 */
	private String otherOrderNo;
	/**
	 * agent用户类型的下单：agent电话号码； 大客户类型的下单：厂商编码（授权码） 散客：空值 		db_column: code 
	 */
	private String code;
	/**
	 * 类型：代理商，厂商； 代理商：A； 厂商：B； 		db_column: type 
	 */
	private String type;
	/**
	 * 订单状态; WATI_PAY（待支付）； WAIT_PICKUP（待取件）； WAIT_SEND（待发货）； SENDED（已发货）； CANCEL（订单取消）; 		db_column: status 
	 */
	private String status;
	/**
	 * 寄件人姓名 		db_column: sender_name 
	 */
	private String senderName;
	/**
	 * 寄件人电话 		db_column: sender_tel 
	 */
	private String senderTel;
	/**
	 * 寄件人地址：省 		db_column: sender_province 
	 */
	private String senderProvince;
	/**
	 * 寄件人地址：城市 		db_column: sender_city 
	 */
	private String senderCity;
	/**
	 * 寄件人地址：区 		db_column: sender_region 
	 */
	private String senderRegion;
	/**
	 * 寄件人地址明细 		db_column: sender_address_detail 
	 */
	private String senderAddressDetail;
	/**
	 * 寄件人邮编 		db_column: sender_zip_code 
	 */
	private String senderZipCode;
	/**
	 * 收件人姓名 		db_column: receiver_name 
	 */
	private String receiverName;
	/**
	 * 收件人电话 		db_column: receiver_tel 
	 */
	private String receiverTel;
	/**
	 * 收件人地址：省 		db_column: receiver_province 
	 */
	private String receiverProvince;
	/**
	 * 收件人地址：城市 		db_column: receiver_city 
	 */
	private String receiverCity;
	/**
	 * 收件人地址：区 		db_column: receiver_region 
	 */
	private String receiverRegion;
	/**
	 * 收件人详细地址 		db_column: receiver_address_detail 
	 */
	private String receiverAddressDetail;
	/**
	 * 收件人邮编 		db_column: receiver_zip_code 
	 */
	private String receiverZipCode;
	/**
	 * 快递公司类型 		db_column: express_type 
	 */
	private String expressType;
	/**
	 * 快递费总价，单位：分 		db_column: total_price 
	 */
	private int totalPrice;
	/**
	 * 创建时间 		db_column: gmt_create 
	 */
	private Date gmtCreate;
	/**
	 * 修改时间 		db_column: gmt_modified 
	 */
	private Date gmtModified;
	/**
	 * 创建人 		db_column: create_by 
	 */
	private String createBy;
	/**
	 * 修改人 		db_column: modify_by 
	 */
	private String modifyBy;

	
	public void setId(long id) {
		this.id = id;
	}
	
	public long getId() {
		return this.id;
	}
	
	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}
	
	public String getOrderNo() {
		return this.orderNo;
	}
	
	public void setOtherOrderNo(String otherOrderNo) {
		this.otherOrderNo = otherOrderNo;
	}
	
	public String getOtherOrderNo() {
		return this.otherOrderNo;
	}
	
	public void setCode(String code) {
		this.code = code;
	}
	
	public String getCode() {
		return this.code;
	}
	
	public void setType(String type) {
		this.type = type;
	}
	
	public String getType() {
		return this.type;
	}
	
	public void setStatus(String status) {
		this.status = status;
	}
	
	public String getStatus() {
		return this.status;
	}
	
	public void setSenderName(String senderName) {
		this.senderName = senderName;
	}
	
	public String getSenderName() {
		return this.senderName;
	}
	
	public void setSenderTel(String senderTel) {
		this.senderTel = senderTel;
	}
	
	public String getSenderTel() {
		return this.senderTel;
	}
	
	public void setSenderProvince(String senderProvince) {
		this.senderProvince = senderProvince;
	}
	
	public String getSenderProvince() {
		return this.senderProvince;
	}
	
	public void setSenderCity(String senderCity) {
		this.senderCity = senderCity;
	}
	
	public String getSenderCity() {
		return this.senderCity;
	}
	
	public void setSenderRegion(String senderRegion) {
		this.senderRegion = senderRegion;
	}
	
	public String getSenderRegion() {
		return this.senderRegion;
	}
	
	public void setSenderAddressDetail(String senderAddressDetail) {
		this.senderAddressDetail = senderAddressDetail;
	}
	
	public String getSenderAddressDetail() {
		return this.senderAddressDetail;
	}
	
	public void setSenderZipCode(String senderZipCode) {
		this.senderZipCode = senderZipCode;
	}
	
	public String getSenderZipCode() {
		return this.senderZipCode;
	}
	
	public void setReceiverName(String receiverName) {
		this.receiverName = receiverName;
	}
	
	public String getReceiverName() {
		return this.receiverName;
	}
	
	public void setReceiverTel(String receiverTel) {
		this.receiverTel = receiverTel;
	}
	
	public String getReceiverTel() {
		return this.receiverTel;
	}
	
	public void setReceiverProvince(String receiverProvince) {
		this.receiverProvince = receiverProvince;
	}
	
	public String getReceiverProvince() {
		return this.receiverProvince;
	}
	
	public void setReceiverCity(String receiverCity) {
		this.receiverCity = receiverCity;
	}
	
	public String getReceiverCity() {
		return this.receiverCity;
	}
	
	public void setReceiverRegion(String receiverRegion) {
		this.receiverRegion = receiverRegion;
	}
	
	public String getReceiverRegion() {
		return this.receiverRegion;
	}
	
	public void setReceiverAddressDetail(String receiverAddressDetail) {
		this.receiverAddressDetail = receiverAddressDetail;
	}
	
	public String getReceiverAddressDetail() {
		return this.receiverAddressDetail;
	}
	
	public void setReceiverZipCode(String receiverZipCode) {
		this.receiverZipCode = receiverZipCode;
	}
	
	public String getReceiverZipCode() {
		return this.receiverZipCode;
	}
	
	public void setExpressType(String expressType) {
		this.expressType = expressType;
	}
	
	public String getExpressType() {
		return this.expressType;
	}
	
	public void setTotalPrice(int totalPrice) {
		this.totalPrice = totalPrice;
	}
	
	public int getTotalPrice() {
		return this.totalPrice;
	}
	
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}
	
	public Date getGmtCreate() {
		return this.gmtCreate;
	}
	
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
	
	public Date getGmtModified() {
		return this.gmtModified;
	}
	
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}
	
	public String getCreateBy() {
		return this.createBy;
	}
	
	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}
	
	public String getModifyBy() {
		return this.modifyBy;
	}

	public String toString() {
		return new ToStringBuilder(this)
			.append("Id",getId())
			.append("OrderNo",getOrderNo())
			.append("OtherOrderNo",getOtherOrderNo())
			.append("Code",getCode())
			.append("Type",getType())
			.append("Status",getStatus())
			.append("SenderName",getSenderName())
			.append("SenderTel",getSenderTel())
			.append("SenderProvince",getSenderProvince())
			.append("SenderCity",getSenderCity())
			.append("SenderRegion",getSenderRegion())
			.append("SenderAddressDetail",getSenderAddressDetail())
			.append("SenderZipCode",getSenderZipCode())
			.append("ReceiverName",getReceiverName())
			.append("ReceiverTel",getReceiverTel())
			.append("ReceiverProvince",getReceiverProvince())
			.append("ReceiverCity",getReceiverCity())
			.append("ReceiverRegion",getReceiverRegion())
			.append("ReceiverAddressDetail",getReceiverAddressDetail())
			.append("ReceiverZipCode",getReceiverZipCode())
			.append("ExpressType",getExpressType())
			.append("TotalPrice",getTotalPrice())
			.append("GmtCreate",getGmtCreate())
			.append("GmtModified",getGmtModified())
			.append("CreateBy",getCreateBy())
			.append("ModifyBy",getModifyBy())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj == null) return false;
		if(this == obj) return true;
		if(obj instanceof ExpressOrderDO == false) return false;
		ExpressOrderDO other = (ExpressOrderDO)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.isEquals();
	}
}

