/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */
package com.zeh.wms.dal.dataobject;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.zeh.jungle.dal.paginator.PageQuery;
import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.jungle.dal.paginator.PageQueryUtils;
/**
 * PaymentOrderDO
 * database table: payment_order
 * database table comments: PaymentOrder
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class PaymentOrderDO implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;
	
	/**
	 * 主键 		db_column: id 
	 */
	private long id;
	/**
	 * 快递单号 		db_column: order_no 
	 */
	private String orderNo;
	/**
	 * 三方快递单号 		db_column: other_order_no 
	 */
	private String otherOrderNo;
	/**
	 * 用户id 		db_column: user_id 
	 */
	private long userId;
	/**
	 * agent用户类型的下单：agent电话号码； 大客户类型的下单：厂商编码（授权码） 散客：空值 		db_column: code 
	 */
	private String code;
	/**
	 * 平台支付流水号 		db_column: payment_order_no 
	 */
	private String paymentOrderNo;
	/**
	 * 微信支付流水号 		db_column: other_payment_no 
	 */
	private String otherPaymentNo;
	/**
	 * 支付金额，单位：分 		db_column: amount 
	 */
	private int amount;
	/**
	 * 打款渠道：WX: 微信; ALIPAY: 支付宝 		db_column: channel 
	 */
	private String channel;
	/**
	 * 支付状态； WATI_PAY（待支付）； PAYING（支付中）； PAYED（已支付）； PAY_CANCEL（支付取消） 		db_column: status 
	 */
	private String status;
	/**
	 * 支付时限，单位：秒 		db_column: pay_limited 
	 */
	private int payLimited;
	/**
	 * 创建时间 		db_column: gmt_create 
	 */
	private Date gmtCreate;
	/**
	 * 修改时间 		db_column: gmt_modified 
	 */
	private Date gmtModified;
	/**
	 * 创建人 		db_column: create_by 
	 */
	private String createBy;
	/**
	 * 修改人 		db_column: modify_by 
	 */
	private String modifyBy;

	
	public void setId(long id) {
		this.id = id;
	}
	
	public long getId() {
		return this.id;
	}
	
	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}
	
	public String getOrderNo() {
		return this.orderNo;
	}
	
	public void setOtherOrderNo(String otherOrderNo) {
		this.otherOrderNo = otherOrderNo;
	}
	
	public String getOtherOrderNo() {
		return this.otherOrderNo;
	}
	
	public void setUserId(long userId) {
		this.userId = userId;
	}
	
	public long getUserId() {
		return this.userId;
	}
	
	public void setCode(String code) {
		this.code = code;
	}
	
	public String getCode() {
		return this.code;
	}
	
	public void setPaymentOrderNo(String paymentOrderNo) {
		this.paymentOrderNo = paymentOrderNo;
	}
	
	public String getPaymentOrderNo() {
		return this.paymentOrderNo;
	}
	
	public void setOtherPaymentNo(String otherPaymentNo) {
		this.otherPaymentNo = otherPaymentNo;
	}
	
	public String getOtherPaymentNo() {
		return this.otherPaymentNo;
	}
	
	public void setAmount(int amount) {
		this.amount = amount;
	}
	
	public int getAmount() {
		return this.amount;
	}
	
	public void setChannel(String channel) {
		this.channel = channel;
	}
	
	public String getChannel() {
		return this.channel;
	}
	
	public void setStatus(String status) {
		this.status = status;
	}
	
	public String getStatus() {
		return this.status;
	}
	
	public void setPayLimited(int payLimited) {
		this.payLimited = payLimited;
	}
	
	public int getPayLimited() {
		return this.payLimited;
	}
	
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}
	
	public Date getGmtCreate() {
		return this.gmtCreate;
	}
	
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
	
	public Date getGmtModified() {
		return this.gmtModified;
	}
	
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}
	
	public String getCreateBy() {
		return this.createBy;
	}
	
	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}
	
	public String getModifyBy() {
		return this.modifyBy;
	}

	public String toString() {
		return new ToStringBuilder(this)
			.append("Id",getId())
			.append("OrderNo",getOrderNo())
			.append("OtherOrderNo",getOtherOrderNo())
			.append("UserId",getUserId())
			.append("Code",getCode())
			.append("PaymentOrderNo",getPaymentOrderNo())
			.append("OtherPaymentNo",getOtherPaymentNo())
			.append("Amount",getAmount())
			.append("Channel",getChannel())
			.append("Status",getStatus())
			.append("PayLimited",getPayLimited())
			.append("GmtCreate",getGmtCreate())
			.append("GmtModified",getGmtModified())
			.append("CreateBy",getCreateBy())
			.append("ModifyBy",getModifyBy())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj == null) return false;
		if(this == obj) return true;
		if(obj instanceof PaymentOrderDO == false) return false;
		PaymentOrderDO other = (PaymentOrderDO)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.isEquals();
	}
}

