/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */
package com.zeh.wms.dal.dataobject;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.zeh.jungle.dal.paginator.PageQuery;
import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.jungle.dal.paginator.PageQueryUtils;
/**
 * QrcodeBatchDO
 * database table: qrcode_batch
 * database table comments: QrcodeBatch
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class QrcodeBatchDO implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;
	
	/**
	 * id 		db_column: id 
	 */
	private long id;
	/**
	 * 批次号 		db_column: batch_serial 
	 */
	private String batchSerial;
	/**
	 * 二维码ID 		db_column: qrcode_serial 
	 */
	private String qrcodeSerial;
	/**
	 * 批次状态； 0-未使用，1-已使用 		db_column: state 
	 */
	private int state;
	/**
	 * 创建时间 		db_column: gmt_create 
	 */
	private Date gmtCreate;
	/**
	 * 更新时间 		db_column: gmt_modified 
	 */
	private Date gmtModified;

	
	public void setId(long id) {
		this.id = id;
	}
	
	public long getId() {
		return this.id;
	}
	
	public void setBatchSerial(String batchSerial) {
		this.batchSerial = batchSerial;
	}
	
	public String getBatchSerial() {
		return this.batchSerial;
	}
	
	public void setQrcodeSerial(String qrcodeSerial) {
		this.qrcodeSerial = qrcodeSerial;
	}
	
	public String getQrcodeSerial() {
		return this.qrcodeSerial;
	}
	
	public void setState(int state) {
		this.state = state;
	}
	
	public int getState() {
		return this.state;
	}
	
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}
	
	public Date getGmtCreate() {
		return this.gmtCreate;
	}
	
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
	
	public Date getGmtModified() {
		return this.gmtModified;
	}

	public String toString() {
		return new ToStringBuilder(this)
			.append("Id",getId())
			.append("BatchSerial",getBatchSerial())
			.append("QrcodeSerial",getQrcodeSerial())
			.append("State",getState())
			.append("GmtCreate",getGmtCreate())
			.append("GmtModified",getGmtModified())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj == null) return false;
		if(this == obj) return true;
		if(obj instanceof QrcodeBatchDO == false) return false;
		QrcodeBatchDO other = (QrcodeBatchDO)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.isEquals();
	}
}

