/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */
package com.zeh.wms.dal.dataobject;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.zeh.jungle.dal.paginator.PageQuery;
import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.jungle.dal.paginator.PageQueryUtils;
/**
 * RegionDO
 * database table: regions
 * database table comments: Region
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class RegionDO implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;
	
	/**
	 * id 		db_column: id 
	 */
	private long id;
	/**
	 * 中国行政编码 		db_column: code 
	 */
	private String code;
	/**
	 * 名称 		db_column: name 
	 */
	private String name;
	/**
	 * 上级行政id 		db_column: parent_id 
	 */
	private long parentId;
	/**
	 * 省市区三个层级 		db_column: level 
	 */
	private int level;
	/**
	 * 拼音首字母 		db_column: first_pinyin_char 
	 */
	private String firstPinyinChar;
	/**
	 * 拼音名称 		db_column: pinyin_name 
	 */
	private String pinyinName;

	
	public void setId(long id) {
		this.id = id;
	}
	
	public long getId() {
		return this.id;
	}
	
	public void setCode(String code) {
		this.code = code;
	}
	
	public String getCode() {
		return this.code;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public String getName() {
		return this.name;
	}
	
	public void setParentId(long parentId) {
		this.parentId = parentId;
	}
	
	public long getParentId() {
		return this.parentId;
	}
	
	public void setLevel(int level) {
		this.level = level;
	}
	
	public int getLevel() {
		return this.level;
	}
	
	public void setFirstPinyinChar(String firstPinyinChar) {
		this.firstPinyinChar = firstPinyinChar;
	}
	
	public String getFirstPinyinChar() {
		return this.firstPinyinChar;
	}
	
	public void setPinyinName(String pinyinName) {
		this.pinyinName = pinyinName;
	}
	
	public String getPinyinName() {
		return this.pinyinName;
	}

	public String toString() {
		return new ToStringBuilder(this)
			.append("Id",getId())
			.append("Code",getCode())
			.append("Name",getName())
			.append("ParentId",getParentId())
			.append("Level",getLevel())
			.append("FirstPinyinChar",getFirstPinyinChar())
			.append("PinyinName",getPinyinName())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj == null) return false;
		if(this == obj) return true;
		if(obj instanceof RegionDO == false) return false;
		RegionDO other = (RegionDO)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.isEquals();
	}
}

