
/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */
package com.zeh.wms.dal.operation.paymentorder;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.zeh.jungle.dal.paginator.PageQuery;
import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.jungle.dal.paginator.PageQueryUtils;
/**
 * database table: payment_order
 * database table comments: PaymentOrder
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class GetAllDataQuery  implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;
	
	/** 快递单号 */
	private String orderNo;
	/** 三方快递单号 */
	private String otherOrderNo;
	/** 用户id */
	private Long userId;
	/** agent用户类型的下单：agent电话号码； 大客户类型的下单：厂商编码（授权码） 散客：空值 */
	private String code;
	/** 平台支付流水号 */
	private String paymentOrderNo;
	/** 微信支付流水号 */
	private String otherPaymentNo;
	/** 支付状态； WATI_PAY（待支付）； PAYING（支付中）； PAYED（已支付）； PAY_CANCEL（支付取消） */
	private String status;
	/** 创建时间 */
	private java.util.Date fromDate;
	/** 创建时间 */
	private java.util.Date toDate;
	
	public GetAllDataQuery() {
	}
	
	public GetAllDataQuery(String orderNo ,String otherOrderNo ,Long userId ,String code ,String paymentOrderNo ,String otherPaymentNo ,String status ,java.util.Date fromDate ,java.util.Date toDate ) {
		this.orderNo = orderNo;
		this.otherOrderNo = otherOrderNo;
		this.userId = userId;
		this.code = code;
		this.paymentOrderNo = paymentOrderNo;
		this.otherPaymentNo = otherPaymentNo;
		this.status = status;
		this.fromDate = fromDate;
		this.toDate = toDate;
	}
	
	public String getOrderNo() {
		return orderNo;
	}
	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}
	public String getOtherOrderNo() {
		return otherOrderNo;
	}
	public void setOtherOrderNo(String otherOrderNo) {
		this.otherOrderNo = otherOrderNo;
	}
	public Long getUserId() {
		return userId;
	}
	public void setUserId(Long userId) {
		this.userId = userId;
	}
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getPaymentOrderNo() {
		return paymentOrderNo;
	}
	public void setPaymentOrderNo(String paymentOrderNo) {
		this.paymentOrderNo = paymentOrderNo;
	}
	public String getOtherPaymentNo() {
		return otherPaymentNo;
	}
	public void setOtherPaymentNo(String otherPaymentNo) {
		this.otherPaymentNo = otherPaymentNo;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public java.util.Date getFromDate() {
		return fromDate;
	}
	public void setFromDate(java.util.Date fromDate) {
		this.fromDate = fromDate;
	}
	public java.util.Date getToDate() {
		return toDate;
	}
	public void setToDate(java.util.Date toDate) {
		this.toDate = toDate;
	}
	
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}
}
