
/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */
package com.zeh.wms.dal.operation.paymentorder;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.zeh.jungle.dal.paginator.PageQuery;
import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.jungle.dal.paginator.PageQueryUtils;
/**
 * database table: payment_order
 * database table comments: PaymentOrder
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class UpdateStatusParameter  implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;
	
	/** 微信支付流水号 */
	private String otherPaymentNo;
	/** 支付状态；WATI_PAY（待支付）；PAYING（支付中）；PAYED（已支付）；PAY_CANCEL（支付取消） */
	private String status;
	/** 修改人 */
	private String modifyBy;
	/** 平台支付流水号 */
	private String paymentOrderNo;
	
	public UpdateStatusParameter() {
	}
	
	public UpdateStatusParameter(String otherPaymentNo ,String status ,String modifyBy ,String paymentOrderNo ) {
		this.otherPaymentNo = otherPaymentNo;
		this.status = status;
		this.modifyBy = modifyBy;
		this.paymentOrderNo = paymentOrderNo;
	}
	
	public String getOtherPaymentNo() {
		return otherPaymentNo;
	}
	public void setOtherPaymentNo(String otherPaymentNo) {
		this.otherPaymentNo = otherPaymentNo;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public String getModifyBy() {
		return modifyBy;
	}
	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}
	public String getPaymentOrderNo() {
		return paymentOrderNo;
	}
	public void setPaymentOrderNo(String paymentOrderNo) {
		this.paymentOrderNo = paymentOrderNo;
	}
	
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}
}
