/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */package com.zeh.wms.dal.daointerface;
import org.springframework.dao.DataAccessException;
import com.zeh.wms.dal.operation.agent.*;
import com.zeh.wms.dal.dataobject.*;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.zeh.jungle.dal.paginator.PageQuery;
import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.jungle.dal.paginator.PageQueryUtils;
/**
 * AgentDAO
 * database table: agent
 * database table comments: Agent
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public interface AgentDAO {


	/**
	 * 
	 * sql:
	 * <pre>INSERT      INTO         agent         (             id ,code ,external_code ,name ,mobile ,address ,gmt_create ,gmt_modified ,create_by ,modify_by             )      VALUES         (?,?,?,?,?,?,?,?,?,?)</pre> 
	 */
	public long insert(AgentDO agent) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>DELETE      FROM         agent      WHERE         id = ?</pre> 
	 */
	public int delete(Long id) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>UPDATE         agent      SET         code = ? ,external_code = ? ,name = ? ,mobile = ? ,address = ? ,gmt_create = ? ,gmt_modified = ? ,create_by = ? ,modify_by = ?                  WHERE         id = ?</pre> 
	 */
	public int update(AgentDO agent) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, code, external_code, name, mobile, address, gmt_create, gmt_modified, create_by, modify_by                       FROM         agent                  WHERE         id = ?</pre> 
	 */
	public AgentDO queryById(Long id) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, code, external_code, name, mobile, address, gmt_create, gmt_modified, create_by, modify_by                       FROM         agent                  WHERE         code = ?</pre> 
	 */
	public AgentDO queryByCode(String code) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, code, external_code, name, mobile, address, gmt_create, gmt_modified, create_by, modify_by                       FROM         agent                  WHERE         1=1                                        AND                      code = ?                                            AND                      external_code = ?                                            AND                      name = ?                                            AND                      mobile = ?                                                ORDER BY         gmt_modified DESC</pre> 
	 */
	public PageList<AgentDO> queryByPage(QueryByPageQuery param) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, code, external_code, name, mobile, address, gmt_create, gmt_modified, create_by, modify_by                       FROM         agent</pre> 
	 */
	public List<AgentDO> getAllEnabled() throws DataAccessException;

}



