/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */package com.zeh.wms.dal.daointerface;
import org.springframework.dao.DataAccessException;
import com.zeh.wms.dal.operation.expres.*;
import com.zeh.wms.dal.dataobject.*;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.zeh.jungle.dal.paginator.PageQuery;
import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.jungle.dal.paginator.PageQueryUtils;
/**
 * ExpresDAO
 * database table: express
 * database table comments: Expres
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public interface ExpresDAO {


	/**
	 * 
	 * sql:
	 * <pre>INSERT      INTO         express         (             name, code, gmt_create, gmt_modified, create_by, modify_by             )      VALUES         (?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,?,?)</pre> 
	 */
	public long insert(ExpresDO expres) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>DELETE      FROM         express      WHERE         id = ?</pre> 
	 */
	public int delete(Long id) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>UPDATE         express      SET         name=?, code = ?,gmt_modified = CURRENT_TIMESTAMP ,modify_by = ?                  WHERE         id = ?</pre> 
	 */
	public int update(ExpresDO expres) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, name, code, gmt_create, gmt_modified, create_by, modify_by                       FROM         express                  WHERE         id = ?</pre> 
	 */
	public ExpresDO queryById(Long id) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, name, code, gmt_create, gmt_modified, create_by, modify_by                       FROM         express                  WHERE         code = ?</pre> 
	 */
	public ExpresDO queryByCode(String code) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, name, code, gmt_create, gmt_modified, create_by, modify_by                       FROM         express                  WHERE         1=1                                        AND                      code = ?                                            AND                      name = ?                                                ORDER BY         gmt_modified DESC</pre> 
	 */
	public PageList<ExpresDO> queryByPage(QueryByPageQuery param) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, name, code, gmt_create, gmt_modified, create_by, modify_by                       FROM         express</pre> 
	 */
	public List<ExpresDO> queryAll() throws DataAccessException;

}



