/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */package com.zeh.wms.dal.daointerface;
import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.wms.dal.dataobject.ExpressOrderDO;
import com.zeh.wms.dal.operation.expressorder.FindPageQuery;
import com.zeh.wms.dal.operation.expressorder.GetAllByParsQuery;
import org.springframework.dao.DataAccessException;

import java.util.List;
/**
 * ExpressOrderDAO
 * database table: express_order
 * database table comments: ExpressOrder
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public interface ExpressOrderDAO {


	/**
	 * 
	 * sql:
	 * <pre>INSERT      INTO         express_order         (           id ,order_no ,other_order_no ,code ,status ,sender_name ,sender_tel ,sender_province ,sender_city ,sender_region ,sender_address_detail ,sender_zip_code ,receiver_name ,receiver_tel ,receiver_province ,receiver_city ,receiver_region ,receiver_address_detail ,receiver_zip_code ,express_type ,total_price ,gmt_create ,gmt_modified ,create_by ,modify_by           )      VALUES         (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)</pre> 
	 */
	public long insert(ExpressOrderDO expressOrder) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>DELETE      FROM         express_order      WHERE         id = ?</pre> 
	 */
	public int delete(Long id) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>UPDATE         express_order      SET         order_no = ? ,other_order_no = ? ,code = ? ,status = ? ,sender_name = ? ,sender_tel = ? ,sender_province = ? ,sender_city = ? ,sender_region = ? ,sender_address_detail = ? ,sender_zip_code = ? ,receiver_name = ? ,receiver_tel = ? ,receiver_province = ? ,receiver_city = ? ,receiver_region = ? ,receiver_address_detail = ? ,receiver_zip_code = ? ,express_type = ? ,total_price = ? ,gmt_create = ? ,gmt_modified = ? ,create_by = ? ,modify_by = ?                WHERE         id = ?</pre> 
	 */
	public int update(ExpressOrderDO expressOrder) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, order_no, other_order_no, code, type, status, sender_name, sender_tel, sender_province, sender_city, sender_region, sender_address_detail, sender_zip_code, receiver_name, receiver_tel, receiver_province, receiver_city, receiver_region, receiver_address_detail, receiver_zip_code, express_type, total_price, gmt_create, gmt_modified, create_by, modify_by                 FROM         express_order                WHERE         id = ?</pre> 
	 */
	public ExpressOrderDO queryById(Long id) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, order_no, other_order_no, code, type, status, sender_name, sender_tel, sender_province, sender_city, sender_region, sender_address_detail, sender_zip_code, receiver_name, receiver_tel, receiver_province, receiver_city, receiver_region, receiver_address_detail, receiver_zip_code, express_type, total_price, gmt_create, gmt_modified, create_by, modify_by           FROM         express_order         WHERE         1=1                               AND                      order_no = ?                                            AND                      other_order_no = ?                                            AND                      code = ?                                            AND                      type = ?                                            AND                      status = ?                                            AND                      receiver_name like concat('%',?,'%')                                            AND                      receiver_tel = ?                                            AND                      express_type = ?                                            AND                                               gmt_create >= ?                                                                 AND                                               gmt_create <= ?</pre> 
	 */
	public PageList<ExpressOrderDO> findPage(FindPageQuery param) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, order_no, other_order_no, code, type, status, sender_name, sender_tel, sender_province, sender_city, sender_region, sender_address_detail, sender_zip_code, receiver_name, receiver_tel, receiver_province, receiver_city, receiver_region, receiver_address_detail, receiver_zip_code, express_type, total_price, gmt_create, gmt_modified, create_by, modify_by           FROM         express_order         WHERE         1=1                   AND       order_no = ?                    AND       other_order_no = ?                    AND       code = ?                    AND       type = ?                    AND       status = ?                    AND       receiver_name like concat('%',?,'%')                    AND       receiver_tel = ?                    AND       express_type = ?                    AND                                gmt_create >= ?                                         AND                                gmt_create <= ?</pre> 
	 */
	public List<ExpressOrderDO> getAllByPars(GetAllByParsQuery param) throws DataAccessException;

}



