/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */package com.zeh.wms.dal.daointerface;
import org.springframework.dao.DataAccessException;
import com.zeh.wms.dal.operation.freight.*;
import com.zeh.wms.dal.dataobject.*;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.zeh.jungle.dal.paginator.PageQuery;
import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.jungle.dal.paginator.PageQueryUtils;
/**
 * FreightDAO
 * database table: freight
 * database table comments: Freight
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public interface FreightDAO {


	/**
	 * 
	 * sql:
	 * <pre>INSERT      INTO         freight         (             id ,province_code ,first_weight ,first_price ,additional_price ,enabled ,gmt_create ,gmt_modified ,create_by ,modify_by             )      VALUES         (?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,?,?)</pre> 
	 */
	public long insert(FreightDO freight) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>DELETE      FROM         freight      WHERE         id = ?</pre> 
	 */
	public int delete(Long id) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>UPDATE         freight      SET         province_code = ? ,first_weight = ? ,first_price = ? ,additional_price = ? ,enabled = ? ,gmt_modified = CURRENT_TIMESTAMP ,modify_by = ?                  WHERE         id = ?</pre> 
	 */
	public int update(FreightDO freight) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, province_code, first_weight, first_price, additional_price, enabled, gmt_create, gmt_modified, create_by, modify_by                       FROM         freight                  WHERE         id = ?</pre> 
	 */
	public FreightDO queryById(Long id) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, province_code, first_weight, first_price, additional_price, enabled, gmt_create, gmt_modified, create_by, modify_by                       FROM         freight                  WHERE         province_code = ?          AND enabled = 1</pre> 
	 */
	public FreightDO queryByProvince(String provinceCode) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, province_code, first_weight, first_price, additional_price, enabled, gmt_create, gmt_modified, create_by, modify_by                       FROM         freight                  WHERE         1=1                                        AND                      province_code = ?                                            AND                      enabled = ?                                                ORDER BY         gmt_modified DESC</pre> 
	 */
	public PageList<FreightDO> queryByPage(QueryByPageQuery param) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, province_code, first_weight, first_price, additional_price, enabled, gmt_create, gmt_modified, create_by, modify_by                       FROM         freight                  WHERE         enabled = 1;</pre> 
	 */
	public List<FreightDO> queryAllEnabled() throws DataAccessException;

}



