/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */package com.zeh.wms.dal.daointerface;
import org.springframework.dao.DataAccessException;
import com.zeh.wms.dal.operation.qrcodebatch.*;
import com.zeh.wms.dal.dataobject.*;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.zeh.jungle.dal.paginator.PageQuery;
import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.jungle.dal.paginator.PageQueryUtils;
/**
 * QrcodeBatchDAO
 * database table: qrcode_batch
 * database table comments: QrcodeBatch
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public interface QrcodeBatchDAO {


	/**
	 * 
	 * sql:
	 * <pre>INSERT      INTO         qrcode_batch         (             id ,batch_serial ,commodity_id ,amount ,state ,gmt_create ,gmt_modified             )      VALUES         (?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)</pre> 
	 */
	public long insert(QrcodeBatchDO qrcodeBatch) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>DELETE      FROM         qrcode_batch      WHERE         id = ?</pre> 
	 */
	public int delete(Long id) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>UPDATE         qrcode_batch      SET         state = ? ,gmt_modified = CURRENT_TIMESTAMP                  WHERE         id = ?</pre> 
	 */
	public int update(QrcodeBatchDO qrcodeBatch) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, batch_serial, commodity_id, amount, state, gmt_create, gmt_modified                       FROM         qrcode_batch                  WHERE         id = ?</pre> 
	 */
	public QrcodeBatchDO queryById(Long id) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, batch_serial, commodity_id, amount, state, gmt_create, gmt_modified                       FROM         qrcode_batch                  WHERE         batch_serial = ?</pre> 
	 */
	public List<QrcodeBatchDO> queryAllQRcodesByBatchSerial(String batchSerial) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, batch_serial, commodity_id, amount, state, gmt_create, gmt_modified                       FROM         qrcode_batch                  WHERE         1=1                                        AND                      batch_serial = ?                                            AND                      state = ?                                                ORDER BY         gmt_modified DESC</pre> 
	 */
	public PageList<QrcodeBatchDO> queryByPage(QueryByPageQuery param) throws DataAccessException;

}



