/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */
package com.zeh.wms.dal.daointerface;

import org.springframework.dao.DataAccessException;

import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.wms.dal.operation.region.QueryByPageQuery;
import com.zeh.wms.dal.operation.region.QueryByPageResult;

/**
 * RegionDAO
 * database table: regions
 * database table comments: Region
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public interface RegionManualDAO {

    PageList<QueryByPageResult> queryByPage(QueryByPageQuery param) throws DataAccessException;

}
