/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */package com.zeh.wms.dal.daointerface;
import org.springframework.dao.DataAccessException;
import com.zeh.wms.dal.operation.region.*;
import com.zeh.wms.dal.dataobject.*;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.zeh.jungle.dal.paginator.PageQuery;
import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.jungle.dal.paginator.PageQueryUtils;
/**
 * RegionDAO
 * database table: regions
 * database table comments: Region
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public interface RegionDAO {


	/**
	 * 
	 * sql:
	 * <pre>INSERT      INTO         regions         (             id ,code ,name ,parent_id ,level ,first_pinyin_char ,pinyin_name             )      VALUES         (?,?,?,?,?,?,?)</pre> 
	 */
	public long insert(RegionDO region) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>DELETE      FROM         regions      WHERE         id = ?</pre> 
	 */
	public int delete(Long id) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>UPDATE         regions      SET         code = ? ,name = ? ,parent_id = ? ,level = ? ,first_pinyin_char = ? ,pinyin_name = ?                  WHERE         id = ?</pre> 
	 */
	public int update(RegionDO region) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, code, name, parent_id, level, first_pinyin_char, pinyin_name                       FROM         regions                  WHERE         id = ?</pre> 
	 */
	public RegionDO queryById(Long id) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, code, name, parent_id, level, first_pinyin_char, pinyin_name                       FROM         regions                  WHERE         code = ?</pre> 
	 */
	public RegionDO queryByCode(String code) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, code, name, parent_id, level, first_pinyin_char, pinyin_name                       FROM         regions                  WHERE         name = ?</pre> 
	 */
	public RegionDO queryByName(String name) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, code, name, parent_id, level, first_pinyin_char, pinyin_name                       FROM         regions                  WHERE         parent_id = ?</pre> 
	 */
	public List<RegionDO> queryByParentId(Long parentId) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, code, name, parent_id, level, first_pinyin_char, pinyin_name                       FROM         regions                  WHERE         1=1                                        AND                      code = ?                                            AND                      name = ?                                            AND                      parent_id = ?                                                ORDER BY         gmt_modified DESC</pre> 
	 */
	public PageList<RegionDO> queryByPage(QueryByPageQuery param) throws DataAccessException;

}



