/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */package com.zeh.wms.dal.daointerface;
import org.springframework.dao.DataAccessException;
import com.zeh.wms.dal.operation.role.*;
import com.zeh.wms.dal.dataobject.*;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.zeh.jungle.dal.paginator.PageQuery;
import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.jungle.dal.paginator.PageQueryUtils;
/**
 * RoleDAO
 * database table: role
 * database table comments: Role
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public interface RoleDAO {


	/**
	 * 
	 * sql:
	 * <pre>INSERT      INTO         role         (             id ,name ,enabled ,gmt_create ,gmt_modified ,create_by ,modify_by             )      VALUES         (?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,?,?)</pre> 
	 */
	public long insert(RoleDO role) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>DELETE      FROM         role      WHERE         id = ?</pre> 
	 */
	public int delete(Long id) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>UPDATE         role      SET         name = ? , enabled = ? ,gmt_modified = CURRENT_TIMESTAMP ,modify_by = ?                  WHERE         id = ?</pre> 
	 */
	public int update(RoleDO role) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, name, enabled, gmt_create, gmt_modified, create_by, modify_by                       FROM         role                  WHERE         id = ?</pre> 
	 */
	public RoleDO queryById(Long id) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, name, enabled, gmt_create, gmt_modified, create_by, modify_by                       FROM         role                  WHERE         name = ?          AND enabled = 1</pre> 
	 */
	public RoleDO queryByName(String name) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, name, enabled, gmt_create, gmt_modified, create_by, modify_by                       FROM         role                  WHERE         1=1                                        AND                      name = ?                                            AND                      enabled = ?                                                ORDER BY         gmt_modified DESC</pre> 
	 */
	public PageList<RoleDO> queryByPage(QueryByPageQuery param) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, name, enabled, gmt_create, gmt_modified, create_by, modify_by                       FROM         role                  WHERE         enabled = 1;</pre> 
	 */
	public List<RoleDO> queryAllEnabled() throws DataAccessException;

}



