/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */package com.zeh.wms.dal.daointerface;
import org.springframework.dao.DataAccessException;
import com.zeh.wms.dal.operation.userbg.*;
import com.zeh.wms.dal.dataobject.*;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.zeh.jungle.dal.paginator.PageQuery;
import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.jungle.dal.paginator.PageQueryUtils;
/**
 * UserBgDAO
 * database table: user_bg
 * database table comments: UserBg
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public interface UserBgDAO {


	/**
	 * 
	 * sql:
	 * <pre>INSERT      INTO         user_bg         (             username ,password ,enabled ,gmt_create ,gmt_modified ,create_by ,modify_by             )      VALUES         (?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,?,?)</pre> 
	 */
	public long insert(UserBgDO userBg) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>DELETE      FROM         user_bg      WHERE         id = ?</pre> 
	 */
	public int delete(Long id) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>UPDATE         user_bg      SET         password = ? , enabled = ?, gmt_modified = CURRENT_TIMESTAMP ,modify_by = ?                  WHERE         id = ?</pre> 
	 */
	public int update(UserBgDO userBg) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, username, password, enabled, gmt_create, gmt_modified, create_by, modify_by                       FROM         user_bg                  WHERE         id = ?</pre> 
	 */
	public UserBgDO queryById(Long id) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, username, password, enabled, gmt_create, gmt_modified, create_by, modify_by                       FROM         user_bg                  WHERE         username = ?</pre> 
	 */
	public UserBgDO queryByUsername(String username) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, username, password, enabled, gmt_create, gmt_modified, create_by, modify_by                       FROM         user_bg                  WHERE         username = ?          AND password = ?</pre> 
	 */
	public UserBgDO queryByLogin(String username ,String password) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, username, password, enabled, gmt_create, gmt_modified, create_by, modify_by                       FROM         user_bg                  WHERE         1=1                                        AND                      username = ?                                            AND                      enabled = ?                                                ORDER BY         gmt_modified DESC</pre> 
	 */
	public PageList<UserBgDO> queryByPage(QueryByPageQuery param) throws DataAccessException;

}



