/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */package com.zeh.wms.dal.daointerface;
import org.springframework.dao.DataAccessException;
import com.zeh.wms.dal.operation.userrolelink.*;
import com.zeh.wms.dal.dataobject.*;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.zeh.jungle.dal.paginator.PageQuery;
import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.jungle.dal.paginator.PageQueryUtils;
/**
 * UserRoleLinkDAO
 * database table: user_role_link
 * database table comments: UserRoleLink
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public interface UserRoleLinkDAO {


	/**
	 * 
	 * sql:
	 * <pre>INSERT      INTO         user_role_link         (             id ,user_id ,role_id ,type             )      VALUES         (?,?,?,?)</pre> 
	 */
	public long insert(UserRoleLinkDO userRoleLink) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>DELETE      FROM         user_role_link      WHERE         id = ?</pre> 
	 */
	public int delete(Long id) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>DELETE      FROM         user_role_link      WHERE         user_id = ?</pre> 
	 */
	public int deleteByUserId(Long userId) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>UPDATE         user_role_link      SET         user_id = ? ,role_id = ? ,type = ?                  WHERE         id = ?</pre> 
	 */
	public int update(UserRoleLinkDO userRoleLink) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, user_id, role_id, type                       FROM         user_role_link                  WHERE         id = ?</pre> 
	 */
	public UserRoleLinkDO queryById(Long id) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         user_id                  FROM         user_role_link                  WHERE         role_id = ?</pre> 
	 */
	public List<Long> queryByRoleId(Long roleId) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         role_id                  FROM         user_role_link                  WHERE         user_id = ?</pre> 
	 */
	public List<Long> queryByUserId(Long userId) throws DataAccessException;

}



