/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */ 
package com.zeh.wms.dal.ibatis;

import com.zeh.wms.dal.daointerface.InventoryHistoryDAO;
import com.zeh.wms.dal.dataobject.InventoryHistoryDO;
import org.springframework.dao.DataAccessException;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import java.util.List;

/**
 * InventoryHistoryDAO
 * database table: inventory_history
 * database table comments: InventoryHistory
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class IbatisInventoryHistoryDAO extends SqlMapClientDaoSupport implements InventoryHistoryDAO {


	/**
	 * 
	 * sql: 
	 * <pre>INSERT      INTO         inventory_history         (             commodity_id,             mobile,             amount,             gmt_create,             gmt_modified,              create_by,             modify_by             )      VALUES         (?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,?,?)</pre>
	 */
	public long insert(InventoryHistoryDO inventoryHistory) throws DataAccessException {
		if(inventoryHistory == null) {
			throw new IllegalArgumentException("Can't insert a null data object into db.");
		}
		getSqlMapClientTemplate().insert("wms.InventoryHistory.insert", inventoryHistory);
		return inventoryHistory.getId();
	}

	/**
	 * 
	 * sql: 
	 * <pre>SELECT         id, commodity_id, mobile, amount, gmt_create, gmt_modified, create_by, modify_by                       FROM         inventory_history                  WHERE         id = ?</pre>
	 */
	public InventoryHistoryDO queryById(Long id) throws DataAccessException {
		return (InventoryHistoryDO)getSqlMapClientTemplate().queryForObject("wms.InventoryHistory.queryById",id);
	}

	/**
	 * 
	 * sql: 
	 * <pre>SELECT         id, commodity_id, mobile, amount, gmt_create, gmt_modified, create_by, modify_by                       FROM         inventory_history                  WHERE         mobile = ?</pre>
	 */
	public List<InventoryHistoryDO> queryByMobile(String mobile) throws DataAccessException {
		return (List<InventoryHistoryDO>)getSqlMapClientTemplate().queryForList("wms.InventoryHistory.queryByMobile",mobile);
	}

}

