/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */ 
package com.zeh.wms.dal.ibatis;

import com.zeh.wms.dal.operation.useragentlink.*;
import com.zeh.wms.dal.dataobject.*;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.zeh.jungle.dal.paginator.PageQuery;
import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.jungle.dal.paginator.PageQueryUtils;
import org.springframework.dao.DataAccessException;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.zeh.wms.dal.dataobject.UserAgentLinkDO;
import com.zeh.wms.dal.daointerface.UserAgentLinkDAO;

/**
 * UserAgentLinkDAO
 * database table: user_agent_link
 * database table comments: UserAgentLink
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class IbatisUserAgentLinkDAO extends SqlMapClientDaoSupport implements UserAgentLinkDAO {


	/**
	 * 
	 * sql: 
	 * <pre>INSERT      INTO         user_agent_link         (           id ,user_id ,code ,type ,link_status ,gmt_create ,gmt_modified ,create_by ,modify_by           )      VALUES         (?,?,?,?,?,?,?,?,?)</pre>
	 */
	public long insert(UserAgentLinkDO userAgentLink) throws DataAccessException {
		if(userAgentLink == null) {
			throw new IllegalArgumentException("Can't insert a null data object into db.");
		}
		getSqlMapClientTemplate().insert("wms.UserAgentLink.insert", userAgentLink);
		return userAgentLink.getId();
	}

	/**
	 * 
	 * sql: 
	 * <pre>DELETE      FROM         user_agent_link      WHERE         id = ?</pre>
	 */
	public int delete(Long id) throws DataAccessException {
		return getSqlMapClientTemplate().delete("wms.UserAgentLink.delete", id);
	}

	/**
	 * 
	 * sql: 
	 * <pre>UPDATE         user_agent_link      SET         user_id = ? ,code = ? ,type = ? ,link_status = ? ,gmt_create = ? ,gmt_modified = ? ,create_by = ? ,modify_by = ?                WHERE         id = ?</pre>
	 */
	public int update(UserAgentLinkDO userAgentLink) throws DataAccessException {
		if(userAgentLink == null) {
			throw new IllegalArgumentException("Can't update by a null data object.");
		}
		return getSqlMapClientTemplate().update("wms.UserAgentLink.update", userAgentLink);
	}

	/**
	 * 
	 * sql: 
	 * <pre>SELECT         id, user_id, code, type, link_status, gmt_create, gmt_modified, create_by, modify_by                  FROM         user_agent_link                WHERE         id = ?</pre>
	 */
	public UserAgentLinkDO queryById(Long id) throws DataAccessException {
		return (UserAgentLinkDO)getSqlMapClientTemplate().queryForObject("wms.UserAgentLink.queryById",id);
	}

	/**
	 * 
	 * sql: 
	 * <pre>SELECT         id, user_id, code, type, link_status, gmt_create, gmt_modified, create_by, modify_by            FROM         user_agent_link</pre>
	 */
	public PageList<UserAgentLinkDO> findPage(int pageSize,int pageNum) throws DataAccessException {
		return PageQueryUtils.pageQuery(getSqlMapClientTemplate(),"wms.UserAgentLink.findPage",null,pageNum,pageSize);
	}

}

