/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */ 
package com.zeh.wms.dal.ibatis;

import com.zeh.wms.dal.operation.auxiliarymaterial.*;
import com.zeh.wms.dal.dataobject.*;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.zeh.jungle.dal.paginator.PageQuery;
import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.jungle.dal.paginator.PageQueryUtils;
import org.springframework.dao.DataAccessException;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.zeh.wms.dal.dataobject.AuxiliaryMaterialDO;
import com.zeh.wms.dal.daointerface.AuxiliaryMaterialDAO;

/**
 * AuxiliaryMaterialDAO
 * database table: auxiliary_material
 * database table comments: AuxiliaryMaterial
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class IbatisAuxiliaryMaterialDAO extends SqlMapClientDaoSupport implements AuxiliaryMaterialDAO {


	/**
	 * 
	 * sql: 
	 * <pre>INSERT      INTO         auxiliary_material         (           id ,name ,price ,quantity ,commodity_id ,gmt_create ,gmt_modified ,create_by ,modified_by           )      VALUES         (?,?,?,?,?,?,?,?,?)</pre>
	 */
	public long insert(AuxiliaryMaterialDO auxiliaryMaterial) throws DataAccessException {
		if(auxiliaryMaterial == null) {
			throw new IllegalArgumentException("Can't insert a null data object into db.");
		}
		getSqlMapClientTemplate().insert("wms.AuxiliaryMaterial.insert", auxiliaryMaterial);
		return auxiliaryMaterial.getId();
	}

	/**
	 * 
	 * sql: 
	 * <pre>DELETE      FROM         auxiliary_material      WHERE         id = ?</pre>
	 */
	public int delete(Long id) throws DataAccessException {
		return getSqlMapClientTemplate().delete("wms.AuxiliaryMaterial.delete", id);
	}

	/**
	 * 
	 * sql: 
	 * <pre>UPDATE         auxiliary_material      SET         name = ? ,price = ? ,quantity = ? ,commodity_id = ? ,gmt_create = ? ,gmt_modified = ? ,create_by = ? ,modified_by = ?                WHERE         id = ?</pre>
	 */
	public int update(AuxiliaryMaterialDO auxiliaryMaterial) throws DataAccessException {
		if(auxiliaryMaterial == null) {
			throw new IllegalArgumentException("Can't update by a null data object.");
		}
		return getSqlMapClientTemplate().update("wms.AuxiliaryMaterial.update", auxiliaryMaterial);
	}

	/**
	 * 
	 * sql: 
	 * <pre>SELECT         id, name, price, quantity, commodity_id, gmt_create, gmt_modified, create_by, modified_by                  FROM         auxiliary_material                WHERE         id = ?</pre>
	 */
	public AuxiliaryMaterialDO queryById(Long id) throws DataAccessException {
		return (AuxiliaryMaterialDO)getSqlMapClientTemplate().queryForObject("wms.AuxiliaryMaterial.queryById",id);
	}

	/**
	 * 
	 * sql: 
	 * <pre>SELECT         id, name, price, quantity, commodity_id, gmt_create, gmt_modified, create_by, modified_by            FROM         auxiliary_material</pre>
	 */
	public PageList<AuxiliaryMaterialDO> findPage(int pageSize,int pageNum) throws DataAccessException {
		return PageQueryUtils.pageQuery(getSqlMapClientTemplate(),"wms.AuxiliaryMaterial.findPage",null,pageNum,pageSize);
	}

}

