/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */ 
package com.zeh.wms.dal.ibatis;

import com.zeh.wms.dal.operation.district.*;
import com.zeh.wms.dal.dataobject.*;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.zeh.jungle.dal.paginator.PageQuery;
import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.jungle.dal.paginator.PageQueryUtils;
import org.springframework.dao.DataAccessException;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.zeh.wms.dal.dataobject.DistrictDO;
import com.zeh.wms.dal.daointerface.DistrictDAO;

/**
 * DistrictDAO
 * database table: district
 * database table comments: District
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class IbatisDistrictDAO extends SqlMapClientDaoSupport implements DistrictDAO {


	/**
	 * 
	 * sql: 
	 * <pre>INSERT      INTO         district         (           id ,code ,name ,gmt_create ,gmt_modified ,create_by ,modify_by           )      VALUES         (?,?,?,?,?,?,?)</pre>
	 */
	public long insert(DistrictDO district) throws DataAccessException {
		if(district == null) {
			throw new IllegalArgumentException("Can't insert a null data object into db.");
		}
		getSqlMapClientTemplate().insert("wms.District.insert", district);
		return district.getId();
	}

	/**
	 * 
	 * sql: 
	 * <pre>DELETE      FROM         district      WHERE         id = ?</pre>
	 */
	public int delete(Long id) throws DataAccessException {
		return getSqlMapClientTemplate().delete("wms.District.delete", id);
	}

	/**
	 * 
	 * sql: 
	 * <pre>UPDATE         district      SET         code = ? ,name = ? ,gmt_create = ? ,gmt_modified = ? ,create_by = ? ,modify_by = ?                WHERE         id = ?</pre>
	 */
	public int update(DistrictDO district) throws DataAccessException {
		if(district == null) {
			throw new IllegalArgumentException("Can't update by a null data object.");
		}
		return getSqlMapClientTemplate().update("wms.District.update", district);
	}

	/**
	 * 
	 * sql: 
	 * <pre>SELECT         id, code, name, gmt_create, gmt_modified, create_by, modify_by                  FROM         district                WHERE         id = ?</pre>
	 */
	public DistrictDO queryById(Long id) throws DataAccessException {
		return (DistrictDO)getSqlMapClientTemplate().queryForObject("wms.District.queryById",id);
	}

	/**
	 * 
	 * sql: 
	 * <pre>SELECT         id, code, name, gmt_create, gmt_modified, create_by, modify_by            FROM         district</pre>
	 */
	public PageList<DistrictDO> findPage(int pageSize,int pageNum) throws DataAccessException {
		return PageQueryUtils.pageQuery(getSqlMapClientTemplate(),"wms.District.findPage",null,pageNum,pageSize);
	}

}

