/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */ 
package com.zeh.wms.dal.ibatis;

import com.zeh.wms.dal.operation.city.*;
import com.zeh.wms.dal.dataobject.*;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.zeh.jungle.dal.paginator.PageQuery;
import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.jungle.dal.paginator.PageQueryUtils;
import org.springframework.dao.DataAccessException;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.zeh.wms.dal.dataobject.CityDO;
import com.zeh.wms.dal.daointerface.CityDAO;

/**
 * CityDAO
 * database table: city
 * database table comments: City
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class IbatisCityDAO extends SqlMapClientDaoSupport implements CityDAO {


	/**
	 * 
	 * sql: 
	 * <pre>INSERT      INTO         city         (           id ,code ,name ,gmt_create ,gmt_modified ,create_by ,modify_by           )      VALUES         (?,?,?,?,?,?,?)</pre>
	 */
	public long insert(CityDO city) throws DataAccessException {
		if(city == null) {
			throw new IllegalArgumentException("Can't insert a null data object into db.");
		}
		getSqlMapClientTemplate().insert("wms.City.insert", city);
		return city.getId();
	}

	/**
	 * 
	 * sql: 
	 * <pre>DELETE      FROM         city      WHERE         id = ?</pre>
	 */
	public int delete(Long id) throws DataAccessException {
		return getSqlMapClientTemplate().delete("wms.City.delete", id);
	}

	/**
	 * 
	 * sql: 
	 * <pre>UPDATE         city      SET         code = ? ,name = ? ,gmt_create = ? ,gmt_modified = ? ,create_by = ? ,modify_by = ?                WHERE         id = ?</pre>
	 */
	public int update(CityDO city) throws DataAccessException {
		if(city == null) {
			throw new IllegalArgumentException("Can't update by a null data object.");
		}
		return getSqlMapClientTemplate().update("wms.City.update", city);
	}

	/**
	 * 
	 * sql: 
	 * <pre>SELECT         id, code, name, gmt_create, gmt_modified, create_by, modify_by                  FROM         city                WHERE         id = ?</pre>
	 */
	public CityDO queryById(Long id) throws DataAccessException {
		return (CityDO)getSqlMapClientTemplate().queryForObject("wms.City.queryById",id);
	}

	/**
	 * 
	 * sql: 
	 * <pre>SELECT         id, code, name, gmt_create, gmt_modified, create_by, modify_by            FROM         city</pre>
	 */
	public PageList<CityDO> findPage(int pageSize,int pageNum) throws DataAccessException {
		return PageQueryUtils.pageQuery(getSqlMapClientTemplate(),"wms.City.findPage",null,pageNum,pageSize);
	}

}

