/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */ 
package com.zeh.wms.dal.ibatis;

import com.zeh.wms.dal.operation.freight.*;
import com.zeh.wms.dal.dataobject.*;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.zeh.jungle.dal.paginator.PageQuery;
import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.jungle.dal.paginator.PageQueryUtils;
import org.springframework.dao.DataAccessException;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.zeh.wms.dal.dataobject.FreightDO;
import com.zeh.wms.dal.daointerface.FreightDAO;

/**
 * FreightDAO
 * database table: freight
 * database table comments: Freight
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class IbatisFreightDAO extends SqlMapClientDaoSupport implements FreightDAO {


	/**
	 * 
	 * sql: 
	 * <pre>INSERT      INTO         freight         (           id ,province_code ,first_weight ,first_price ,additional_price ,gmt_create ,gmt_modified ,create_by ,modify_by           )      VALUES         (?,?,?,?,?,?,?,?,?)</pre>
	 */
	public long insert(FreightDO freight) throws DataAccessException {
		if(freight == null) {
			throw new IllegalArgumentException("Can't insert a null data object into db.");
		}
		getSqlMapClientTemplate().insert("wms.Freight.insert", freight);
		return freight.getId();
	}

	/**
	 * 
	 * sql: 
	 * <pre>DELETE      FROM         freight      WHERE         id = ?</pre>
	 */
	public int delete(Long id) throws DataAccessException {
		return getSqlMapClientTemplate().delete("wms.Freight.delete", id);
	}

	/**
	 * 
	 * sql: 
	 * <pre>UPDATE         freight      SET         province_code = ? ,first_weight = ? ,first_price = ? ,additional_price = ? ,gmt_create = ? ,gmt_modified = ? ,create_by = ? ,modify_by = ?                WHERE         id = ?</pre>
	 */
	public int update(FreightDO freight) throws DataAccessException {
		if(freight == null) {
			throw new IllegalArgumentException("Can't update by a null data object.");
		}
		return getSqlMapClientTemplate().update("wms.Freight.update", freight);
	}

	/**
	 * 
	 * sql: 
	 * <pre>SELECT         id, province_code, first_weight, first_price, additional_price, gmt_create, gmt_modified, create_by, modify_by                  FROM         freight                WHERE         id = ?</pre>
	 */
	public FreightDO queryById(Long id) throws DataAccessException {
		return (FreightDO)getSqlMapClientTemplate().queryForObject("wms.Freight.queryById",id);
	}

	/**
	 * 
	 * sql: 
	 * <pre>SELECT         id, province_code, first_weight, first_price, additional_price, gmt_create, gmt_modified, create_by, modify_by            FROM         freight</pre>
	 */
	public PageList<FreightDO> findPage(int pageSize,int pageNum) throws DataAccessException {
		return PageQueryUtils.pageQuery(getSqlMapClientTemplate(),"wms.Freight.findPage",null,pageNum,pageSize);
	}

}

