/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */ 
package com.zeh.wms.dal.ibatis;

import com.zeh.wms.dal.operation.region.*;
import com.zeh.wms.dal.dataobject.*;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.zeh.jungle.dal.paginator.PageQuery;
import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.jungle.dal.paginator.PageQueryUtils;
import org.springframework.dao.DataAccessException;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.zeh.wms.dal.dataobject.RegionDO;
import com.zeh.wms.dal.daointerface.RegionDAO;

/**
 * RegionDAO
 * database table: regions
 * database table comments: Region
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class IbatisRegionDAO extends SqlMapClientDaoSupport implements RegionDAO {


	/**
	 * 
	 * sql: 
	 * <pre>INSERT      INTO         regions         (             id ,code ,name ,parent_id ,level ,first_pinyin_char ,pinyin_name             )      VALUES         (?,?,?,?,?,?,?)</pre>
	 */
	public long insert(RegionDO region) throws DataAccessException {
		if(region == null) {
			throw new IllegalArgumentException("Can't insert a null data object into db.");
		}
		getSqlMapClientTemplate().insert("wms.Region.insert", region);
		return region.getId();
	}

	/**
	 * 
	 * sql: 
	 * <pre>DELETE      FROM         regions      WHERE         id = ?</pre>
	 */
	public int delete(Long id) throws DataAccessException {
		return getSqlMapClientTemplate().delete("wms.Region.delete", id);
	}

	/**
	 * 
	 * sql: 
	 * <pre>UPDATE         regions      SET         code = ? ,name = ? ,parent_id = ? ,level = ? ,first_pinyin_char = ? ,pinyin_name = ?                  WHERE         id = ?</pre>
	 */
	public int update(RegionDO region) throws DataAccessException {
		if(region == null) {
			throw new IllegalArgumentException("Can't update by a null data object.");
		}
		return getSqlMapClientTemplate().update("wms.Region.update", region);
	}

	/**
	 * 
	 * sql: 
	 * <pre>SELECT         id, code, name, parent_id, level, first_pinyin_char, pinyin_name                       FROM         regions                  WHERE         id = ?</pre>
	 */
	public RegionDO queryById(Long id) throws DataAccessException {
		return (RegionDO)getSqlMapClientTemplate().queryForObject("wms.Region.queryById",id);
	}

	/**
	 * 
	 * sql: 
	 * <pre>SELECT         id, code, name, parent_id, level, first_pinyin_char, pinyin_name                       FROM         regions                  WHERE         code = ?</pre>
	 */
	public RegionDO queryByCode(String code) throws DataAccessException {
		return (RegionDO)getSqlMapClientTemplate().queryForObject("wms.Region.queryByCode",code);
	}

	/**
	 * 
	 * sql: 
	 * <pre>SELECT         id, code, name, parent_id, level, first_pinyin_char, pinyin_name                       FROM         regions                  WHERE         name = ?</pre>
	 */
	public RegionDO queryByName(String name) throws DataAccessException {
		return (RegionDO)getSqlMapClientTemplate().queryForObject("wms.Region.queryByName",name);
	}

	/**
	 * 
	 * sql: 
	 * <pre>SELECT         id, code, name, parent_id, level, first_pinyin_char, pinyin_name                       FROM         regions                  WHERE         parent_id = ?</pre>
	 */
	public List<RegionDO> queryByParentId(Long parentId) throws DataAccessException {
		return (List<RegionDO>)getSqlMapClientTemplate().queryForList("wms.Region.queryByParentId",parentId);
	}

}

