
/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */
package com.zeh.wms.dal.operation.expressorder;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.zeh.jungle.dal.paginator.PageQuery;
import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.jungle.dal.paginator.PageQueryUtils;
/**
 * database table: express_order
 * database table comments: ExpressOrder
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class GetAllByParsQuery  implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;
	
	/** 快递单号 */
	private String orderNo;
	/** 3方订单号 */
	private String otherOrderNo;
	/** 用户ID */
	private Long userId;
	/** 结算方式： ONLINE("ONLINE", "在线支付"), OFFLINE("OFFLINE", "线下现付"), MONTHLY("MONTHLY", "线下月结"); */
	private String paymentType;
	/** 订单状态;WATI_PAY（待支付-线上支付）；WAIT_PICKUP（待取件）；WAIT_SEND（待发货）；SENDED（已发货）；CANCEL（订单取消）; */
	private String status;
	/** 创建时间 */
	private java.util.Date fromDate;
	/** 创建时间 */
	private java.util.Date toDate;
	
	public GetAllByParsQuery() {
	}
	
	public GetAllByParsQuery(String orderNo ,String otherOrderNo ,Long userId ,String paymentType ,String status ,java.util.Date fromDate ,java.util.Date toDate ) {
		this.orderNo = orderNo;
		this.otherOrderNo = otherOrderNo;
		this.userId = userId;
		this.paymentType = paymentType;
		this.status = status;
		this.fromDate = fromDate;
		this.toDate = toDate;
	}
	
	public String getOrderNo() {
		return orderNo;
	}
	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}
	public String getOtherOrderNo() {
		return otherOrderNo;
	}
	public void setOtherOrderNo(String otherOrderNo) {
		this.otherOrderNo = otherOrderNo;
	}
	public Long getUserId() {
		return userId;
	}
	public void setUserId(Long userId) {
		this.userId = userId;
	}
	public String getPaymentType() {
		return paymentType;
	}
	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public java.util.Date getFromDate() {
		return fromDate;
	}
	public void setFromDate(java.util.Date fromDate) {
		this.fromDate = fromDate;
	}
	public java.util.Date getToDate() {
		return toDate;
	}
	public void setToDate(java.util.Date toDate) {
		this.toDate = toDate;
	}
	
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}
}
