
/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */
package com.zeh.wms.dal.operation.expressorder;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.zeh.jungle.dal.paginator.PageQuery;
import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.jungle.dal.paginator.PageQueryUtils;
/**
 * database table: express_order
 * database table comments: ExpressOrder
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class UpdateCommodityWeightAndPriceParameter  implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;
	
	/** 商品总重量 */
	private Integer commodityWeight;
	/** 首重，单位（克） */
	private Integer firstWeight;
	/** 续重，单位：克 */
	private Integer additionalWeight;
	/** 首重价格，单位：分 */
	private Integer firstWeightPrice;
	/** 续重价格，单位：分 */
	private String additionalWeightPrice;
	/** 快递费总价，单位：分 */
	private Integer totalPrice;
	/** 订单状态;WATI_PAY（待支付-线上支付）；WAIT_PICKUP（待取件）；WAIT_SEND（待发货）；SENDED（已发货）；CANCEL（订单取消）; */
	private String status;
	/** 修改人 */
	private String modifyBy;
	/** 快递单号 */
	private String orderNo;
	
	public UpdateCommodityWeightAndPriceParameter() {
	}
	
	public UpdateCommodityWeightAndPriceParameter(Integer commodityWeight ,Integer firstWeight ,Integer additionalWeight ,Integer firstWeightPrice ,String additionalWeightPrice ,Integer totalPrice ,String status ,String modifyBy ,String orderNo ) {
		this.commodityWeight = commodityWeight;
		this.firstWeight = firstWeight;
		this.additionalWeight = additionalWeight;
		this.firstWeightPrice = firstWeightPrice;
		this.additionalWeightPrice = additionalWeightPrice;
		this.totalPrice = totalPrice;
		this.status = status;
		this.modifyBy = modifyBy;
		this.orderNo = orderNo;
	}
	
	public Integer getCommodityWeight() {
		return commodityWeight;
	}
	public void setCommodityWeight(Integer commodityWeight) {
		this.commodityWeight = commodityWeight;
	}
	public Integer getFirstWeight() {
		return firstWeight;
	}
	public void setFirstWeight(Integer firstWeight) {
		this.firstWeight = firstWeight;
	}
	public Integer getAdditionalWeight() {
		return additionalWeight;
	}
	public void setAdditionalWeight(Integer additionalWeight) {
		this.additionalWeight = additionalWeight;
	}
	public Integer getFirstWeightPrice() {
		return firstWeightPrice;
	}
	public void setFirstWeightPrice(Integer firstWeightPrice) {
		this.firstWeightPrice = firstWeightPrice;
	}
	public String getAdditionalWeightPrice() {
		return additionalWeightPrice;
	}
	public void setAdditionalWeightPrice(String additionalWeightPrice) {
		this.additionalWeightPrice = additionalWeightPrice;
	}
	public Integer getTotalPrice() {
		return totalPrice;
	}
	public void setTotalPrice(Integer totalPrice) {
		this.totalPrice = totalPrice;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public String getModifyBy() {
		return modifyBy;
	}
	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}
	public String getOrderNo() {
		return orderNo;
	}
	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}
	
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}
}
