
/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */
package com.zeh.wms.dal.operation.region;

import java.io.Serializable;

import org.apache.commons.lang.builder.ToStringBuilder;

import com.zeh.jungle.dal.paginator.PageQuery;

/**
 * database table: manufacturer
 * database table comments: Manufacturer
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class QueryByPageQuery extends PageQuery implements Serializable {
    private static final long serialVersionUID = -5216457518046898601L;

    /** 厂商编号 */
    private String            code;
    /** name */
    private String            name;
    private Long              parentId;

    public QueryByPageQuery() {
    }

    public QueryByPageQuery(String code, String name, Long parentId) {
        this.code = code;
        this.name = name;
        this.parentId = parentId;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getParentId() {
        return parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this);
    }
}
