
/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */
package com.zeh.wms.dal.operation.inventory;

import org.apache.commons.lang.builder.ToStringBuilder;
/**
 * database table: inventory
 * database table comments: Inventory
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class GetInfoByMobileQuery  implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;
	
	/** 用户电话 */
	private String mobile;
	/** id */
	private Long id;
	/** 客户姓名 */
	private String name;
	
	public GetInfoByMobileQuery() {
	}
	
	public GetInfoByMobileQuery(String mobile ,Long id ,String name ) {
		this.mobile = mobile;
		this.id = id;
		this.name = name;
	}
	
	public String getMobile() {
		return mobile;
	}
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}
}
