

/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */
package com.zeh.wms.dal.operation.inventory;

import org.apache.commons.lang.builder.ToStringBuilder;
/**
 * database table: inventory
 * database table comments: Inventory
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class GetInfoByMobileResult implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;
	
	/** id */
	private long id;
	/** 商品id */
	private long commodityId;
	/** 用户电话 */
	private String mobile;
	/** 库存数量 */
	private int amount;
	/** 商品编号 */
	private String code;
	/** 商品名称 */
	private String name;
	/** 商品单价，单位：分 */
	private int price;
	/** 商品单位，如：件，箱 */
	private String unit;
	/** 商品重量（单件），单位：克 */
	private int weight;
	/** 商品简介 */
	private String description;
	/** 厂商ID */
	private long manufacturerId;

	public void setId(long id) {
		this.id = id;
	}
	
	public long getId() {
		return this.id;
	}
	
	public void setCommodityId(long commodityId) {
		this.commodityId = commodityId;
	}
	
	public long getCommodityId() {
		return this.commodityId;
	}
	
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
	
	public String getMobile() {
		return this.mobile;
	}
	
	public void setAmount(int amount) {
		this.amount = amount;
	}
	
	public int getAmount() {
		return this.amount;
	}
	
	public void setCode(String code) {
		this.code = code;
	}
	
	public String getCode() {
		return this.code;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public String getName() {
		return this.name;
	}
	
	public void setPrice(int price) {
		this.price = price;
	}
	
	public int getPrice() {
		return this.price;
	}
	
	public void setUnit(String unit) {
		this.unit = unit;
	}
	
	public String getUnit() {
		return this.unit;
	}
	
	public void setWeight(int weight) {
		this.weight = weight;
	}
	
	public int getWeight() {
		return this.weight;
	}
	
	public void setDescription(String description) {
		this.description = description;
	}
	
	public String getDescription() {
		return this.description;
	}
	
	public void setManufacturerId(long manufacturerId) {
		this.manufacturerId = manufacturerId;
	}
	
	public long getManufacturerId() {
		return this.manufacturerId;
	}
	

	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}
	
}
