
/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */
package com.zeh.wms.dal.operation.qrcodebatch;

import com.zeh.jungle.dal.paginator.PageQuery;
import org.apache.commons.lang.builder.ToStringBuilder;
/**
 * database table: qrcode_batch
 * database table comments: QrcodeBatch
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class QueryByPageQuery  extends PageQuery implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;
	
	/** 批次号 */
	private String batchSerial;
	/** 批次状态； 0-未使用，1-已使用 */
	private Integer state;
	/** 批次数量 */
	private Integer amount;
	
	public QueryByPageQuery() {
	}
	
	public QueryByPageQuery(String batchSerial ,Integer state ) {
		this.batchSerial = batchSerial;
		this.state = state;
	}
	
	public String getBatchSerial() {
		return batchSerial;
	}
	public void setBatchSerial(String batchSerial) {
		this.batchSerial = batchSerial;
	}
	public Integer getState() {
		return state;
	}
	public void setState(Integer state) {
		this.state = state;
	}
	
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}

	public Integer getAmount() {
		return amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}
}
