
/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */
package com.zeh.wms.dal.operation.inventoryhistory;

import com.zeh.jungle.dal.paginator.PageQuery;
import org.apache.commons.lang.builder.ToStringBuilder;
/**
 * database table: inventory_history
 * database table comments: InventoryHistory
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class QueryHistoryQuery  extends PageQuery implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;
	
	/** mobile */
	private Object mobile;
	/** nickName */
	private Object nickName;
	/** commodityId */
	private Object commodityId;
	/** 修改时间 */
	private java.util.Date fromDate;
	/** 修改时间 */
	private java.util.Date toDate;
	
	public QueryHistoryQuery() {
	}
	
	public QueryHistoryQuery(Object mobile ,Object nickName ,Object commodityId ,java.util.Date fromDate ,java.util.Date toDate ) {
		this.mobile = mobile;
		this.nickName = nickName;
		this.commodityId = commodityId;
		this.fromDate = fromDate;
		this.toDate = toDate;
	}
	
	public Object getMobile() {
		return mobile;
	}
	public void setMobile(Object mobile) {
		this.mobile = mobile;
	}
	public Object getNickName() {
		return nickName;
	}
	public void setNickName(Object nickName) {
		this.nickName = nickName;
	}
	public Object getCommodityId() {
		return commodityId;
	}
	public void setCommodityId(Object commodityId) {
		this.commodityId = commodityId;
	}
	public java.util.Date getFromDate() {
		return fromDate;
	}
	public void setFromDate(java.util.Date fromDate) {
		this.fromDate = fromDate;
	}
	public java.util.Date getToDate() {
		return toDate;
	}
	public void setToDate(java.util.Date toDate) {
		this.toDate = toDate;
	}
	
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}
}
