

/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */
package com.zeh.wms.dal.operation.inventoryhistory;

import org.apache.commons.lang.builder.ToStringBuilder;
/**
 * database table: inventory_history
 * database table comments: InventoryHistory
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class QueryHistoryResult implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;
	
	/** id */
	private long id;
	/** 商品id */
	private long commodityId;
	/** 电话 */
	private String mobile;
	/** amount */
	private int amount;
	/** 创建时间 */
	private java.util.Date gmtCreate;
	/** 修改时间 */
	private java.util.Date gmtModified;
	/** 创建人 */
	private String createBy;
	/** 修改人 */
	private String modifyBy;
	/** 昵称 */
	private String nickName;
	/** commodityName */
	private String commodityName;

	public void setId(long id) {
		this.id = id;
	}
	
	public long getId() {
		return this.id;
	}
	
	public void setCommodityId(long commodityId) {
		this.commodityId = commodityId;
	}
	
	public long getCommodityId() {
		return this.commodityId;
	}
	
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
	
	public String getMobile() {
		return this.mobile;
	}
	
	public void setAmount(int amount) {
		this.amount = amount;
	}
	
	public int getAmount() {
		return this.amount;
	}
	
	public void setGmtCreate(java.util.Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}
	
	public java.util.Date getGmtCreate() {
		return this.gmtCreate;
	}
	
	public void setGmtModified(java.util.Date gmtModified) {
		this.gmtModified = gmtModified;
	}
	
	public java.util.Date getGmtModified() {
		return this.gmtModified;
	}
	
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}
	
	public String getCreateBy() {
		return this.createBy;
	}
	
	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}
	
	public String getModifyBy() {
		return this.modifyBy;
	}
	
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}
	
	public String getNickName() {
		return this.nickName;
	}
	
	public void setCommodityName(String commodityName) {
		this.commodityName = commodityName;
	}
	
	public String getCommodityName() {
		return this.commodityName;
	}
	

	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}
	
}
