

/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */
package com.zeh.wms.dal.operation.freight;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.zeh.jungle.dal.paginator.PageQuery;
import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.jungle.dal.paginator.PageQueryUtils;
/**
 * database table: freight
 * database table comments: Freight
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class GetPriceByProvinceNameResult implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;
	
	/** 主键 */
	private long id;
	/** 省编码 */
	private String provinceCode;
	/** 快递公司类型,SF-顺丰，DEPPON-德邦  */
	private String expressCode;
	/** 首重，单位：500克 */
	private int firstWeight;
	/** 首重每500克单价原价，单价：分 */
	private int firstOriginalPrice;
	/** 续重每500克原始价格，单位：分 */
	private int additionalOriginalPrice;
	/** 首重每500克单价成本价，单价：分 */
	private int firstCostPrice;
	/** 续重每500克成本价格，单位：分 */
	private int additionalCostPrice;
	/** 启用状态，0-未启用，1-已启用 */
	private int enabled;
	/** 创建时间 */
	private java.util.Date gmtCreate;
	/** 修改时间 */
	private java.util.Date gmtModified;
	/** 创建人 */
	private String createBy;
	/** 修改人 */
	private String modifyBy;

	public void setId(long id) {
		this.id = id;
	}
	
	public long getId() {
		return this.id;
	}
	
	public void setProvinceCode(String provinceCode) {
		this.provinceCode = provinceCode;
	}
	
	public String getProvinceCode() {
		return this.provinceCode;
	}
	
	public void setExpressCode(String expressCode) {
		this.expressCode = expressCode;
	}
	
	public String getExpressCode() {
		return this.expressCode;
	}
	
	public void setFirstWeight(int firstWeight) {
		this.firstWeight = firstWeight;
	}
	
	public int getFirstWeight() {
		return this.firstWeight;
	}
	
	public void setFirstOriginalPrice(int firstOriginalPrice) {
		this.firstOriginalPrice = firstOriginalPrice;
	}
	
	public int getFirstOriginalPrice() {
		return this.firstOriginalPrice;
	}
	
	public void setAdditionalOriginalPrice(int additionalOriginalPrice) {
		this.additionalOriginalPrice = additionalOriginalPrice;
	}
	
	public int getAdditionalOriginalPrice() {
		return this.additionalOriginalPrice;
	}
	
	public void setFirstCostPrice(int firstCostPrice) {
		this.firstCostPrice = firstCostPrice;
	}
	
	public int getFirstCostPrice() {
		return this.firstCostPrice;
	}
	
	public void setAdditionalCostPrice(int additionalCostPrice) {
		this.additionalCostPrice = additionalCostPrice;
	}
	
	public int getAdditionalCostPrice() {
		return this.additionalCostPrice;
	}
	
	public void setEnabled(int enabled) {
		this.enabled = enabled;
	}
	
	public int getEnabled() {
		return this.enabled;
	}
	
	public void setGmtCreate(java.util.Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}
	
	public java.util.Date getGmtCreate() {
		return this.gmtCreate;
	}
	
	public void setGmtModified(java.util.Date gmtModified) {
		this.gmtModified = gmtModified;
	}
	
	public java.util.Date getGmtModified() {
		return this.gmtModified;
	}
	
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}
	
	public String getCreateBy() {
		return this.createBy;
	}
	
	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}
	
	public String getModifyBy() {
		return this.modifyBy;
	}
	

	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}
	
}
