
/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */
package com.zeh.wms.dal.operation.useragentlink;

import org.apache.commons.lang.builder.ToStringBuilder;
/**
 * database table: user_agent_link
 * database table comments: UserAgentLink
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class QueryByParQuery  implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;
	
	/** 用户表主键 */
	private Long userId;
	/** agent电话号码，或厂商编码（授权码） */
	private String code;
	/** 类型：代理商，厂商；代理商：A；厂商：B； */
	private String type;
	/** 关联关系状态：1已关联, 0已解除； 已关联：Y； 已解除：N； */
	private Integer linkStatus;
	
	public QueryByParQuery() {
	}
	
	public QueryByParQuery(Long userId ,String code ,String type ,Integer linkStatus ) {
		this.userId = userId;
		this.code = code;
		this.type = type;
		this.linkStatus = linkStatus;
	}
	
	public Long getUserId() {
		return userId;
	}
	public void setUserId(Long userId) {
		this.userId = userId;
	}
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public Integer getLinkStatus() {
		return linkStatus;
	}
	public void setLinkStatus(Integer linkStatus) {
		this.linkStatus = linkStatus;
	}
	
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}
}
