/**
 * Jungle.com Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */ 
package com.zeh.wms.wms.dal.ibatis;

import com.zeh.wms.wms.dal.operation.manufacturer.*;
import com.zeh.wms.wms.dal.dataobject.*;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.zeh.jungle.dal.paginator.PageQuery;
import com.zeh.jungle.dal.paginator.PageList;
import com.zeh.jungle.dal.paginator.PageQueryUtils;
import org.springframework.dao.DataAccessException;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.zeh.wms.wms.dal.dataobject.ManufacturerDO;
import com.zeh.wms.wms.dal.daointerface.ManufacturerDAO;

/**
 * ManufacturerDAO
 * database table: manufacturer
 * database table comments: Manufacturer
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class IbatisManufacturerDAO extends SqlMapClientDaoSupport implements ManufacturerDAO {


	/**
	 * 
	 * sql: 
	 * <pre>INSERT      INTO         manufacturer         (           id ,serial_id ,name          )      VALUES         (?,?,?)</pre>
	 */
	public long insert(ManufacturerDO manufacturer) throws DataAccessException {
		if(manufacturer == null) {
			throw new IllegalArgumentException("Can't insert a null data object into db.");
		}
		getSqlMapClientTemplate().insert("wms.Manufacturer.insert", manufacturer);
		return manufacturer.getId();
	}

	/**
	 * 
	 * sql: 
	 * <pre>DELETE      FROM         manufacturer      WHERE         id = ?</pre>
	 */
	public int delete(Long id) throws DataAccessException {
		return getSqlMapClientTemplate().delete("wms.Manufacturer.delete", id);
	}

	/**
	 * 
	 * sql: 
	 * <pre>UPDATE         manufacturer      SET         serial_id = ? ,name = ?               WHERE         id = ?</pre>
	 */
	public int update(ManufacturerDO manufacturer) throws DataAccessException {
		if(manufacturer == null) {
			throw new IllegalArgumentException("Can't update by a null data object.");
		}
		return getSqlMapClientTemplate().update("wms.Manufacturer.update", manufacturer);
	}

	/**
	 * 
	 * sql: 
	 * <pre>SELECT         id, serial_id, name                 FROM         manufacturer               WHERE         id = ?</pre>
	 */
	public ManufacturerDO queryById(Long id) throws DataAccessException {
		return (ManufacturerDO)getSqlMapClientTemplate().queryForObject("wms.Manufacturer.queryById",id);
	}

	/**
	 * 
	 * sql: 
	 * <pre>SELECT         id, serial_id, name           FROM         manufacturer</pre>
	 */
	public PageList<ManufacturerDO> findPage(int pageSize,int pageNum) throws DataAccessException {
		return PageQueryUtils.pageQuery(getSqlMapClientTemplate(),"wms.Manufacturer.findPage",null,pageNum,pageSize);
	}

}

